# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QMessageBox
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtGui import QIcon,QPixmap, QIntValidator, QFocusEvent
from mbrawo import Ui_Form
from mfalse import Ui_Form_False
import random



class Calculation():

    def add(self, a, b):
        result = a + b
        return result

    def substract(self, a, b):
        if a > b or a == b:
            result = a - b
        else:
            result = b - a
        return result

    def multiply(self, a, b):
        result = a * b
        return result

    def division(self, a, b):
        result = a / b
        return result


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 499)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.newButton = QtWidgets.QPushButton(self.centralwidget)
        self.newButton.setGeometry(QtCore.QRect(30, 20, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.newButton.setFont(font)
        self.newButton.setObjectName("newButton")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(550, 400, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.checkButton.setFont(font)
        self.checkButton.setObjectName("checkButton")
        self.labelEqual = QtWidgets.QLabel(self.centralwidget)
        self.labelEqual.setGeometry(QtCore.QRect(500, 150, 141, 111))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.labelEqual.setFont(font)
        self.labelEqual.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelEqual.setIndent(46)
        self.labelEqual.setObjectName("labelEqual")

        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(500, 230, 500, 150))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1.setIndent(46)
        self.label_1.setObjectName("label_1")
        

        self.labelL = QtWidgets.QLabel(self.centralwidget)
        self.labelL.setGeometry(QtCore.QRect(50, 140, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelL.setFont(font)
        self.labelL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelL.setLineWidth(1)
        self.labelL.setMidLineWidth(0)
        self.labelL.setIndent(1)
        self.labelL.setObjectName("labelL")
        self.labelMark = QtWidgets.QLabel(self.centralwidget)
        self.labelMark.setGeometry(QtCore.QRect(210, 140, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(70)
        self.labelMark.setFont(font)
        self.labelMark.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelMark.setLineWidth(1)
        self.labelMark.setMidLineWidth(0)
        self.labelMark.setIndent(50)
        self.labelMark.setObjectName("labelMark")
        self.labelP = QtWidgets.QLabel(self.centralwidget)
        self.labelP.setGeometry(QtCore.QRect(370, 140, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.labelP.setFont(font)
        self.labelP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelP.setLineWidth(1)
        self.labelP.setMidLineWidth(0)
        self.labelP.setIndent(1)
        self.labelP.setObjectName("labelP")
        self.lineEditR = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditR.setGeometry(QtCore.QRect(630, 140, 151, 141))
        font = QtGui.QFont()
        font.setPointSize(100)

        self.lineEditR.setFont(font)
        self.lineEditR.setObjectName("lineEditR")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #Field limits
        self.lineEditR.setMaxLength(4)
        self.lineEditR.setValidator(QIntValidator(0,1000))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.newButton.clicked.connect(self.calc_view)
        self.checkButton.clicked.connect(self.check)
        self.lineEditR.returnPressed.connect(self.check)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        self.newButton.setText(_translate("MainWindow", "Nowe zadanie"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        self.newButton.setText(_translate("MainWindow", "Nowe zadanie"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        self.newButton.setText(_translate("MainWindow", "Nowe zadanie"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.newButton.setText(_translate("MainWindow", "Nowe zadanie"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        self.newButton.setText(_translate("MainWindow", "Nowe zadanie"))
        _translate = QtCore.QCoreApplication.translate
        self.checkButton.setText(_translate("MainWindow", "Sprawdź"))
        self.labelEqual.setText(_translate("MainWindow", "="))
        self.labelL.setText(_translate("MainWindow", ""))
        self.labelMark.setText(_translate("MainWindow", ""))
        self.labelP.setText(_translate("MainWindow", ""))
        self.lineEditR.setText(_translate("MainWindow", ""))
        self.label_1.setText(_translate("MainWindow", "Zatwierdź wynik ENTEREM"))


    def calc_view(self):

        print("funkcja calc_view")

        calc = Calculation()
        a = random.randint(0, 20)
        b = random.randint(0, 20)
        action_dict = {calc.add(a, b): "+",
                       calc.substract(a, b): "-",
         #             calc.multiply(a,b): "*",
         #             calc.division(a,b): "/"
                    }
        self.action = random.choice(list(action_dict))
        print("self.action = ", self.action)
        mark = action_dict[self.action]
        self.result = self.action


        if a < b:
            self.labelL.setNum(b)
            self.labelMark.setText(mark)
            self.labelP.setNum(a)
            self.lineEditR.setText("")
        else:
            self.labelL.setNum(a)
            self.labelMark.setText(mark)
            self.labelP.setNum(b)
            self.lineEditR.setText("")


    def brawoscr(self):
        print ("funkcja bwaroscr")
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()

    def falsescr(self):
        print ("funkcja falsescr")
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form_False()
        self.ui.setupUi(self.Form)
        self.Form.show()


    def check(self):

        print ("funkcja check")

        result = self.action
        man_result = int(self.lineEditR.text())

        if man_result == result:
            self.checkButton.clicked.connect(self.brawoscr)

            print ("man result = ", man_result)
        else:
            self.checkButton.clicked.connect(self.falsescr)

            print ("man result falszywy = ", man_result)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
